services:
  db:
    image: postgres:16
    container_name: project_db
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: BeC9AL2l
      POSTGRES_DB: strapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
